// Code generated by qtc from "editProduct.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Page of product edit
//

//line ../templates/editProduct.qtpl:3
package templates

//line ../templates/editProduct.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../templates/editProduct.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../templates/editProduct.qtpl:4
type ProductEditPage struct {
	Name  string
	Price int
}

//line ../templates/editProduct.qtpl:10
func (p *ProductEditPage) StreamBody(qw422016 *qt422016.Writer) {
//line ../templates/editProduct.qtpl:10
	qw422016.N().S(`
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
    <h5 id="error"></h5>

    <form id="form">
        <input type="text" name="name" placeholder="Name" value="`)
//line ../templates/editProduct.qtpl:21
	qw422016.E().S(p.Name)
//line ../templates/editProduct.qtpl:21
	qw422016.N().S(`">
        <input type="number" name="price" placeholder="Price" value="`)
//line ../templates/editProduct.qtpl:22
	qw422016.N().D(p.Price)
//line ../templates/editProduct.qtpl:22
	qw422016.N().S(`">

        <button type="submit">Сохранить</button>
    </form>

    <a href="/products">
        <button type="button">Отмена</button>
    </a>
</body>

<script>
    var form = document.getElementById('form');
    form.addEventListener('submit', function(event) {
        event.preventDefault();

        var formData = new FormData(form), result = {};
        chunks = window.location.href.split("product/edit/");
        result["id"] = parseInt(chunks[chunks.length - 1]);
        for (var entry of formData.entries()) {
            result[entry[0]] = entry[1];
        }

        var xmlHttp = new XMLHttpRequest();
        xmlHttp.open("PUT", "/cmd/edit-product", false);
        xmlHttp.send(JSON.stringify(result));

        var jsonData = JSON.parse(xmlHttp.responseText);
        if (jsonData.status === "failure") {
            document.getElementById("error").innerHTML = jsonData.error;
        } else {
            window.location.replace("/products");
        }
    });
</script>

</html>
`)
//line ../templates/editProduct.qtpl:58
}

//line ../templates/editProduct.qtpl:58
func (p *ProductEditPage) WriteBody(qq422016 qtio422016.Writer) {
//line ../templates/editProduct.qtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../templates/editProduct.qtpl:58
	p.StreamBody(qw422016)
//line ../templates/editProduct.qtpl:58
	qt422016.ReleaseWriter(qw422016)
//line ../templates/editProduct.qtpl:58
}

//line ../templates/editProduct.qtpl:58
func (p *ProductEditPage) Body() string {
//line ../templates/editProduct.qtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
//line ../templates/editProduct.qtpl:58
	p.WriteBody(qb422016)
//line ../templates/editProduct.qtpl:58
	qs422016 := string(qb422016.B)
//line ../templates/editProduct.qtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
//line ../templates/editProduct.qtpl:58
	return qs422016
//line ../templates/editProduct.qtpl:58
}
