// Code generated by qtc from "errPage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Page of error
//

//line ../templates/errPage.qtpl:3
package templates

//line ../templates/errPage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../templates/errPage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../templates/errPage.qtpl:4
type ErrPage struct {
	Error string
}

//line ../templates/errPage.qtpl:9
func (p *ErrPage) StreamBody(qw422016 *qt422016.Writer) {
//line ../templates/errPage.qtpl:9
	qw422016.N().S(`
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
    <h5>`)
//line ../templates/errPage.qtpl:17
	qw422016.E().S(p.Error)
//line ../templates/errPage.qtpl:17
	qw422016.N().S(`</h5>
</body>

</html>
`)
//line ../templates/errPage.qtpl:21
}

//line ../templates/errPage.qtpl:21
func (p *ErrPage) WriteBody(qq422016 qtio422016.Writer) {
//line ../templates/errPage.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../templates/errPage.qtpl:21
	p.StreamBody(qw422016)
//line ../templates/errPage.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line ../templates/errPage.qtpl:21
}

//line ../templates/errPage.qtpl:21
func (p *ErrPage) Body() string {
//line ../templates/errPage.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line ../templates/errPage.qtpl:21
	p.WriteBody(qb422016)
//line ../templates/errPage.qtpl:21
	qs422016 := string(qb422016.B)
//line ../templates/errPage.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line ../templates/errPage.qtpl:21
	return qs422016
//line ../templates/errPage.qtpl:21
}
